services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_frontend
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
